baseURL = "https://ghostbasenji.github.io/"
languageCode = "ru-ru"
title = "–ó–∞–ø–∏—Å–∫–∏ –Ω–∞—á–∏–Ω–∞—é—à–µ–≥–æ –ø—Ä–æ–≥—Ä–∞–º–º–∏—Å—Ç–∞"
theme = "anatole"

[params]
title = "I'm Ghost Basenji"
author = "Ghost Basenji"
description = "–ù–∞—á–∏–Ω–∞—é—â–∏–π –ø—Ä–æ–≥—Ä–∞–º–º–∏—Å—Ç"
profilePicture = "images/profile.png"
contentratio = 0.75

displayMode = "light"
disableThemeSwitcher = true
doNotLoadAnimations = true
enableMediumZoom = false

reversepagetitle = true
disableTitleCapitalization = true
disableArchiveTitleStyling = true
hidesidebar = false

summarylength = 10
readMore = true
mainSections = ["post"]

enableEmoji = true
enableRobotsTXT = true

customCss = ["css/syntax.css"]

[[params.socialIcons]]
icon = "fab fa-telegram"
title = "Telegram"
url = "https://t.me/ghostbasenji"

[[params.socialIcons]]
icon = "fa fa-envelope"
title = "e-mail"
url = "petr.and.vic@gmail.com"

[[params.socialIcons]]
title = "github"
icon = "fa-brands fa-github"
url = "https://github.com/GhostBasenji"

[menu]
  [[menu.main]]
  name = "–ì–ª–∞–≤–Ω–∞—è"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "–ü–æ—Å—Ç—ã"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "–°–µ—Ä–∏–∏"
  weight = 300
  identifier = "series"
  url = "/series/"

  [[menu.main]]
  name = "–¢–µ–≥–∏"
  weight = 400
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

copyright = "{{ YEAR }}"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

# Mermaid
[params.mermaid]
enable = true

# Markdown / Goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

  [markup.highlight]
    noClasses = false           # ‚ùå –ò—Å–ø–æ–ª—å–∑—É–µ–º CSS-–∫–ª–∞—Å—Å—ã, –∞ –Ω–µ inline-—Å—Ç–∏–ª–∏
    style = "vs" # üé® –°—Ç–∏–ª—å –ø–æ–¥—Å–≤–µ—Ç–∫–∏ Chroma
    guessSyntax = false
